export const dummyCategories = [
  "Photographer",
  "Videographer",
  "Graphic Designer",
  "Web Developer",
  "Digital Marketer",
  "Content Writer",
  "Event Planner",
  "Makeup Artist",
  "Hair Stylist",
  "Personal Trainer",
  "Tutor",
  "Interior Designer",
  "Home Services",
  "Legal Professional",
  "Financial Consultant",
  "Musician",
  "Health Assistance",
];
